name: conda_venv
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=pyhf64b827_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - anyio=4.12.1=pyhcf101f3_0
  - applaunchservices=0.3.0=pyh534df25_4
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py314h6482030_2
  - arrow=1.4.0=pyhcf101f3_0
  - astroid=4.0.3=py314hee6578b_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.1.0=pyhcf101f3_0
  - async-timeout=5.0.1=pyhcf101f3_2
  - asyncssh=2.21.1=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - autopep8=2.0.4=pyhd8ed1ab_0
  - aws-c-auth=0.9.3=hdff831d_0
  - aws-c-cal=0.9.13=hea39f9f_1
  - aws-c-common=0.12.6=h8616949_0
  - aws-c-compression=0.3.1=h901532c_9
  - aws-c-event-stream=0.5.7=ha05da6a_1
  - aws-c-http=0.10.7=h924c446_5
  - aws-c-io=0.23.3=hf559bb5_5
  - aws-c-mqtt=0.13.3=ha72ff4e_11
  - aws-c-s3=0.11.3=he30762a_1
  - aws-c-sdkutils=0.2.4=h901532c_4
  - aws-checksums=0.2.7=h901532c_5
  - aws-crt-cpp=0.35.4=h7484968_0
  - aws-sdk-cpp=1.11.606=h386ebac_10
  - azure-core-cpp=1.16.1=he2a98a9_0
  - azure-identity-cpp=1.13.2=h0e8e1c8_1
  - azure-storage-blobs-cpp=12.16.0=ha4e89a6_0
  - azure-storage-common-cpp=12.12.0=h2a5eb39_0
  - azure-storage-files-datalake-cpp=12.14.0=h7f37a48_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhcf101f3_2
  - backports.zstd=1.3.0=py314h680f03e_0
  - bcrypt=5.0.0=py314ha7b6dee_1
  - beautifulsoup4=4.14.3=pyha770c72_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - black=26.1.0=pyh866005b_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - bokeh=3.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=hf139dec_1
  - brotli-bin=1.2.0=h8616949_1
  - brotli-python=1.2.0=py314h3262eb8_1
  - bzip2=1.0.8=h500dc9f_8
  - c-ares=1.34.6=hb5e19a0_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cattrs=25.3.0=pyhd8ed1ab_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py314h8ca4d5a_1
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py314h22a2ed9_4
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cpython=3.14.3=py314hd8ed1ab_100
  - cryptography=46.0.4=py314h6a45124_0
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=h610c526_0
  - cytoolz=1.1.0=py314h6482030_1
  - dask=2026.1.2=pyhcf101f3_0
  - dask-core=2026.1.2=pyhcf101f3_0
  - debugpy=1.8.20=py314h2f9fc56_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_1
  - diff-match-patch=20241021=pyhd8ed1ab_1
  - dill=0.4.1=pyhcf101f3_0
  - distributed=2026.1.2=pyhcf101f3_0
  - docstring-to-markdown=0.17=pyhe01879c_0
  - docutils=0.22.4=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - flake8=7.1.2=pyhd8ed1ab_0
  - fonttools=4.61.1=pyh7db6752_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h694c41f_0
  - frozenlist=1.7.0=pyhf298e5d_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - fzf=0.67.0=h1ecb644_0
  - gflags=2.2.2=hac325c4_1005
  - giflib=5.2.2=h10d778d_0
  - glib=2.86.3=h182e902_0
  - glib-tools=2.86.3=h8650975_0
  - glog=0.7.1=h2790a97_0
  - gst-plugins-base=1.24.11=h09840cc_0
  - gstreamer=1.24.11=h7d1b200_0
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.11=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflection=0.5.1=pyhd8ed1ab_1
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.31.0=pyh5552912_0
  - ipython=9.10.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - isort=7.0.0=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhcf101f3_3
  - jaraco.context=6.1.0=pyhcf101f3_0
  - jaraco.functools=4.4.0=pyhcf101f3_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jellyfish=1.2.1=py314hc9c287a_1
  - jinja2=3.1.6=pyhcf101f3_1
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - jupyterlab=4.5.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - keyring=25.7.0=pyh534df25_0
  - kiwisolver=1.4.9=py314hf3ac25a_2
  - krb5=1.21.3=h37d8d59_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.18=h90db99b_0
  - lerc=4.0.0=hcca01a6_1
  - libabseil=20250512.1=cxx17_hfc00f1c_0
  - libarrow=23.0.0=h8071b21_1_cpu
  - libarrow-acero=23.0.0=h9737151_1_cpu
  - libarrow-compute=23.0.0=hc26cc94_1_cpu
  - libarrow-dataset=23.0.0=h9737151_1_cpu
  - libarrow-substrait=23.0.0=h7f2e36e_1_cpu
  - libblas=3.11.0=5_he492b99_openblas
  - libbrotlicommon=1.2.0=h8616949_1
  - libbrotlidec=1.2.0=h8616949_1
  - libbrotlienc=1.2.0=h8616949_1
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libclang-cpp18.1=18.1.8=default_hc369343_17
  - libclang13=21.1.8=default_h5e75a71_3
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.18.0=h9348e2b_0
  - libcxx=21.1.8=h4fb565c_2
  - libdeflate=1.25=h517ebb2_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libexpat=2.7.3=heffb93a_0
  - libffi=3.5.2=hd1f9c09_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgcc=15.2.0=h08519bb_17
  - libgfortran=15.2.0=h7e5c614_17
  - libgfortran5=15.2.0=hd16e46c_17
  - libglib=2.86.3=hf241ffe_0
  - libgoogle-cloud=2.39.0=hed66dea_0
  - libgoogle-cloud-storage=2.39.0=h8ac052b_0
  - libgrpc=1.73.1=h451496d_1
  - libiconv=1.18=h57a12c2_2
  - libintl=0.25.1=h3184127_1
  - libintl-devel=0.25.1=h3184127_1
  - libjpeg-turbo=3.1.2=h8616949_0
  - liblapack=3.11.0=5_h859234e_openblas
  - libllvm18=18.1.8=default_hc369343_11
  - libllvm21=21.1.8=h56e7563_0
  - liblzma=5.8.2=h11316ed_0
  - libmpdec=4.0.0=hf3981d6_1
  - libnghttp2=1.67.0=h3338091_0
  - libntlm=1.8=h6e16a3a_0
  - libogg=1.3.5=he3325bb_1
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libopentelemetry-cpp=1.21.0=h7d3f41d_1
  - libopentelemetry-cpp-headers=1.21.0=h694c41f_1
  - libopus=1.6.1=hc6ced15_0
  - libparquet=23.0.0=ha0d2768_1_cpu
  - libpng=1.6.54=h07817ec_0
  - libpq=18.1=h1e038c5_2
  - libprotobuf=6.31.1=hcc66ac3_4
  - libre2-11=2025.11.05=h554ac88_0
  - libsodium=1.0.20=hfdf4475_0
  - libspatialindex=2.1.0=h501a4e1_0
  - libsqlite=3.51.2=hb99441e_0
  - libssh2=1.11.1=hed3591d_0
  - libthrift=0.22.0=h687e942_1
  - libtiff=4.7.1=ha0a348c_1
  - libutf8proc=2.11.3=hc282952_0
  - libvorbis=1.3.7=ha059160_2
  - libwebp=1.6.0=h5442d53_0
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.15.1=h7b7ecba_0
  - libxml2-16=2.15.1=ha1d9b0f_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.8=h472b3d1_0
  - llvmlite=0.46.0=py314h85c3bf0_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lsprotocol=2025.0.0=pyhe01879c_0
  - lz4=4.4.5=py314h6bf1ee8_1
  - lz4-c=1.10.0=h240833e_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=pyh7db6752_0
  - matplotlib=3.10.8=py314hee6578b_0
  - matplotlib-base=3.10.8=py314hd47142c_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.2.0=pyhcf101f3_0
  - more-itertools=10.8.0=pyhcf101f3_1
  - msgpack-python=1.1.2=py314h00ed6fe_1
  - multidict=6.7.0=pyh62beb40_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - narwhals=2.16.0=pyhcf101f3_0
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert=7.17.0=h14065e2_0
  - nbconvert-core=7.17.0=pyhcf101f3_0
  - nbconvert-pandoc=7.17.0=hc3985f0_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h06076ce_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nspr=4.38=hee0b3f1_0
  - nss=3.118=h2b2a826_0
  - numba=0.63.1=py314h385e359_0
  - numpy=2.3.5=py314hfc4c462_1
  - numpydoc=1.10.0=pyhcf101f3_0
  - openjpeg=2.5.4=h87e8dc5_0
  - openldap=2.6.10=hd8a590d_0
  - openssl=3.6.1=hb6871ef_1
  - orc=2.2.2=h3073fbf_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py314h550b3c8_0
  - pandoc=3.9=h694c41f_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pathspec=1.0.4=pyhd8ed1ab_0
  - pcre2=10.47=h13923f0_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.1.0=py314hf9dbaa9_0
  - pip=26.0.1=pyh145f28c_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - ply=3.11=pyhd8ed1ab_3
  - prometheus-cpp=1.3.0=h7802330_0
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=pyhe1237c8_0
  - psutil=7.2.2=py314hd330473_0
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=23.0.0=py314hee6578b_0
  - pyarrow-core=23.0.0=py314h27d7cfc_0_cpu
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.8.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.11.0=pyhd8ed1ab_0
  - pylint=4.0.4=pyhcf101f3_0
  - pylint-venv=3.0.4=pyhd8ed1ab_1
  - pyls-spyder=0.4.0=pyhd8ed1ab_1
  - pynacl=1.6.2=py314h4f144dc_0
  - pyobjc-core=12.1=py314h681fd4f_0
  - pyobjc-framework-cocoa=12.1=py314h9720295_0
  - pyobjc-framework-coreservices=12.1=py314h6482030_2
  - pyobjc-framework-fsevents=12.1=py314hee6578b_2
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyqt=5.15.11=py314hf791c31_2
  - pyqt5-sip=12.17.0=py314h0c8d1e5_2
  - pyqtwebengine=5.15.11=py314hb52c834_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.14.3=h4f44bb5_100_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.14.3=h4df99d1_100
  - python-gssapi=1.11.1=py314hcc71bfa_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-ruff=2.3.0=pyhcf101f3_0
  - python-lsp-server=1.14.0=pyh332efcf_0
  - python-lsp-server-base=1.14.0=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python.app=1.4=py314h03d016b_5
  - python_abi=3.14=8_cp314
  - pytokens=0.3.0=pyhcf101f3_0
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pytz=2025.2=pyhd8ed1ab_0
  - pyuca=1.2=pyhd8ed1ab_2
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0.3=py314h10d0514_1
  - pyzmq=27.1.0=py312hb7d603e_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_1
  - qhull=2020.2=h3c5361c_5
  - qstylizer=0.2.4=pyhff2d567_0
  - qt-main=5.15.15=hf9f191d_6
  - qt-webengine=5.15.15=h46887bd_1
  - qtawesome=1.4.1=pyh9208f05_0
  - qtconsole=5.7.0=pyhd8ed1ab_0
  - qtconsole-base=5.7.0=pyha770c72_0
  - qtpy=2.4.3=pyhd8ed1ab_1
  - re2=2025.11.05=h7df6414_0
  - readline=8.3=h68b038d_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.3.2=pyhcf101f3_0
  - roman-numerals=4.1.0=pyhd8ed1ab_0
  - rope=1.14.0=pyhd8ed1ab_0
  - rpds-py=0.30.0=py314ha7b6dee_0
  - rtree=1.4.1=pyh11ca60a_0
  - ruff=0.15.0=h5930b28_0
  - scipy=1.17.0=py314h6328ba2_1
  - send2trash=2.1.0=pyh5552912_0
  - setuptools=80.10.2=pyh332efcf_0
  - sip=6.10.0=py314h21b9a27_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h01f5ddf_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - sphinx=9.1.0=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - spyder=6.1.2=hd8ed1ab_0
  - spyder-base=6.1.2=osx_pyh1a5313d_0
  - spyder-kernels=3.1.2=unix_pyh707e725_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - superqt=0.7.8=pyh9208f05_0
  - tblib=3.2.2=pyhcf101f3_0
  - terminado=0.18.1=pyhc90fa1f_1
  - text-unidecode=1.3=pyhd8ed1ab_2
  - textdistance=4.6.3=pyhd8ed1ab_1
  - three-merge=0.1.1=pyhd8ed1ab_1
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=h7142dee_3
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.4.0=pyhcf101f3_0
  - tomlkit=0.14.0=pyha770c72_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py314h3d180e3_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - ujson=5.11.0=py314h6cc4523_1
  - unicodedata2=17.0.0=py314h6482030_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - watchdog=6.0.0=py314h6482030_2
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - whatthepatch=1.0.7=pyhd8ed1ab_1
  - wrapt=2.1.1=py314h4f144dc_0
  - wurlitzer=3.1.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h4132b18_3
  - yapf=0.43.0=pyhd8ed1ab_1
  - yarl=1.22.0=pyh7db6752_0
  - zeromq=4.3.5=h6c33b1e_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hd23fc13_2
  - zlib-ng=2.3.3=h8bce59a_1
  - zstd=1.5.7=h3eecb57_6
prefix: /Users/astatham/miniforge3/envs/conda_venv
